# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8227c9c23595cb82431cf65f741408ce48ab087004615dfbaa8cb198a99322d19d557ad32a7925d3062e6cd59299f906e191cf442e4e1eee92909bf90e9f8c9

test:
  secret_key_base: 08b029c2e0f7ca2274037707274d2a795d7fc3e01bb45b2ba9cc35de218e9b751a8a4b14031bdccae355e24388317282f28afb72e10262ca2c6cdeb2eaf1c553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
